useDotenv: true

service: poprox-persona-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  versionFunctions: false
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  memorySize: 2048 # 2gb
  timeout: 25
  architecture: x86_64
  environment:
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    POPROX_TEST_PERSONA: "false"
    POPROX_DEFAULT_PIPELINE: "persona_recommender"

  iam:
    role:
      # Add statements to the IAM role to give permissions to Lambda functions
      statements:
        - Effect: Allow
          Action:
            - "logs:*"
          Resource: "*"

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      poprox-persona:
        path: "./"
        platform: linux/amd64
        buildArgs:
          AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
          AWS_SESSION_TOKEN: ${env:AWS_SESSION_TOKEN}

package:
  patterns:
    - "!venv/**"
    - "!models/**"
    - "!node_modules/**"
    - "!tests/**"
    - "**.py"
    - "**.html"

functions:
  generateRecommendations:
    image:
      name: poprox-persona
    memorySize: 4096
    ephemeralStorageSize: 2048
    events:
      - httpApi:
          path: /warmup
          method: get
      - httpApi:
          path: /
          method: post
